### ISSUE TITLE
Undefined function 'getRunningApp' for input arguments of type 'GUI_Syre'.

### ISSUE THREAD

**Issue by KMoula30** [SyR-e/syre_public#1]
Hello great work on the tool !

When i try to run GUI_Syre or GUI_Syre_MMM this error occurs:
Error in GUI_Syre (line 8735)
            runningApp = getRunningApp(app);
I run the R2019b Matlab version.
Keep up the good work!

**Comment by SimFerr** [comment]
Hello,
thanks for the appreciation and sorry for the late reply.

I think there are some issues with this Matlab version (and its AppDesigner). Try the compatibility files stored in ReadMe\Matlab2019b_AppDesigner_compatibility.zip. This could help!

Best
Simone
