### ISSUE TITLE
SyR-e on Octave

### ISSUE THREAD

**Issue by tatiano** [SyR-e/syre_public#2]
Hi! Do the GUI_Syre and GUI_Syre_MMM also run on Octave or they are only available for Matlab?
If is there a way to run them in Octave, could you please give some insights on how to run it. Unfortunately, I couldn't figure out how to do that based on the documentation.
Thanks in advance and congrats for the excellent work.

**Comment by SimFerr** [comment]
Hello,
thanks!
Unfortunately, the GUIs are developed with Matlab AppDesigner and, based on what I know, there are no compatibility with Octave. With Octave you must go for the "Working without GUI" (see Chapter 7 of the user manual), but it is less intuitive than the use of the graphical interfaces.

Best,
Simone
