### ISSUE TITLE
The equation to calculate the phase resistance is not clear (calc_i0.m)

### ISSUE THREAD

**Issue by yahiagio** [SyR-e/syre_public#3]
Hello i hope your are doing well.
 i dont understand how did you get this expression for the phase resistance? 
 Rs   = 12.rocu.(l+lend)/(kcu.Aslots).Ns^2; 

my calculations:  
Lmt : mean length turn of the coil = 2.(l+lend)  ;with l=stack length , lend=end turn length. 
S : section of the copper conductor = Aslot.Kcu/(Ns/q.p) ; wtih Ns=number of turns in series per phase, q=number of slots per pole per phase , p=number of pole pairs.  Ns/(q.p) the number of conductors in each slot. 

Rs=rocu.Lmt/S.Ns
so Rs=rocu.2.(l+lend)/(Aslot.Kcu.q.p).Ns^2 

its the not the same equation as yours ??? how did you get your expression please and how we check if it is correct ?

**Comment by SimFerr** [comment]
Hello,
your equation is correct, but the difference is the slot area considered. In the equation used in SyR-e, the total slot area (Aslots) is considered, so Aslots=6*p*q*Aslot. If you substitute this expression in you equation, you'll find the equation included in SyR-e.

Best,
Simone

**Comment by yahiagio** [comment]
Thnak you so much!
